syntax = "proto3";

package xray.app.proxyman.command;

service HandlerService {
  rpc AddInbound (AddInboundRequest) returns (AddInboundResponse);
  rpc RemoveInbound (RemoveInboundRequest) returns (RemoveInboundResponse);
  rpc AlterInbound (AlterInboundRequest) returns (AlterInboundResponse);
  rpc AddUser (AddUserRequest) returns (AddUserResponse);
  rpc RemoveUser (RemoveUserRequest) returns (RemoveUserResponse);
}

message AddUserRequest {
  string tag = 1;
  User user = 2;
}

message User {
  string email = 1;
  Account account = 2;
}

message Account {
  string id = 1;
  string alterId = 2;
  string security = 3;
}

message AddUserResponse {}

message RemoveUserRequest {
  string tag = 1;
  string email = 2;
}

message RemoveUserResponse {}

message AddInboundRequest {
  InboundObject inbound = 1;
}

message AddInboundResponse {}

message RemoveInboundRequest {
  string tag = 1;
}

message RemoveInboundResponse {}

message AlterInboundRequest {
  string tag = 1;
  string operation = 2;
  string value = 3;
}

message AlterInboundResponse {}

message InboundObject {
  string tag = 1;
  string protocol = 2;
  string listen = 3;
  uint32 port = 4;
  bytes settings = 5;
  bytes streamSettings = 6;
}
